kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: web3-node
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 8545
        protocol: TCP
      - containerPort: 30002
        hostPort: 8546
        protocol: TCP
      - containerPort: 30003
        hostPort: 6060
        protocol: TCP
